version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 726652658490.dkr.ecr.ap-south-1.amazonaws.com
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=726652658490.dkr.ecr.ap-south-1.amazonaws.com/ecs-cicd
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR_Core_Artifacts
      - ls
      - mvn clean install
      - cd $CODEBUILD_SRC_DIR
      - ls
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t ecs-cicd:latest .
      - docker tag ecs-cicd:latest REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push REPOSITORY_URI:latest
#artifacts:
  #files:
    #- target/aws-sdk.tar.gz
    #- scripts/deploy.sh
    #- appspec.yml
  #discard-paths: yes
cache:
  paths:
    - '/ec2-user/.m2/**/*'
    - '/root/.m2/**/*'

