server:
  port: 8081
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    thymeleaf:
      enabled: true
      encoding: utf-8
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
      cache: false
  security:
    user:
      name: root
      password: root
      roles: ADMIN
  profiles:
    active: dev
    #active: prod
    #active: qa

